name: Generate Doxygen Documentation

on:
  push:
    branches:
      - Small

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Doxygen
        run: |
          sudo apt-get install doxygen graphviz

      - name: Generate documentation
        run: |
          doxygen Simple/Doxyfile

      - name: Commit documentation
        run: |
          mkdir doc
          cd doc
          git init
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Update documentation [skip ci]"

      - name: Push to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote add origin https://github.com/${{ github.repository }}.git
          git push -u origin master --force

